---
title: "Plot_results"
output: html_document
date: "2024-08-12"
---
# Libraries
```{r}
library(data.table)
library(pheatmap)
library(tidyverse)
library(gridExtra)
library(ggpubr)
```

# Read in data and format data
```{r}
setwd("C://Users//Jessie PC//OneDrive - University of North Carolina at Chapel Hill//Symbolic_regression_github//NIH_Cloud_NOSI")

# Read in results
results_pysr <- read.csv('..\\NIH_Cloud_NOSI\\Models\\1_Simulated_data\\pysr\\results_pysr.csv')
results_gplearn <- read.csv('..\\NIH_Cloud_NOSI\\Models\\1_Simulated_data\\gplearn\\results_gplearn.csv')
results_feyn <- read.csv('..\\NIH_Cloud_NOSI\\Models\\1_Simulated_data\\feyn\\results_feyn.csv')

# Combine results into one data frame
results_list <- list(results_gplearn, results_pysr, results_feyn)
names(results_list) <- c('gplearn', 'pysr', 'feyn')

# Add operator complexity
for(i in 1:length(results_list)){
  temp <- results_list[[i]]
  
  # Make operator column consistent
  if(i==2){
    temp <- temp %>%
      mutate(Operators = paste0(Binary.operators, Unary.Operators)) %>%
      select(-Binary.operators, -Unary.Operators)
  }
  
  # Add complexity level
  temp$Operator_complexity <- 'Low'
  temp$Operator_complexity[11:20] <- 'Medium'
  temp$Operator_complexity[21:30] <- 'High'
  
  # Add package name
  temp$Package <- names(results_list)[i]
  
  # Append to list 
  results_list[[i]] <- temp
}

# Combine into one data frame
results_all <- do.call(bind_rows, results_list)
results_all$Level <- paste0(results_all$Package, results_all$Operator_complexity)
```

# Create RMSE heatmap
```{r}
# Convert to wide format for RMSE heatmap
rmse_wide <- results_all %>%
  select(Input, Level, RMSE) %>%
  pivot_wider(names_from = Input, values_from = RMSE) 

# Define the desired order for rows and columns
row_order <- c('gplearnHigh', 'pysrHigh', 'feynHigh', 'gplearnMedium', 'pysrMedium', 'feynMedium', 'gplearnLow','pysrLow','feynLow')
column_order <- c('No_noise_rel_var', 'No_noise_all_var', 'Noise=0.25', 'Noise=0.5', 'Noise=0.75', 'Noise=1', 'Noise=1.25', 'Noise=1.5', 'Noise=1.75', 'Noise=2')

# Reorder rows and columns
rmse_wide <- rmse_wide[match(row_order, rmse_wide$Level), ]
rmse_wide <- rmse_wide[, c("Level", column_order), with = FALSE]

# Set row names for pheatmap
rows <- c('gplearn', 'PySR', 'feyn', 'gplearn ', 'PySR ', 'feyn ', 'gplearn  ', 'PySR  ', 'feyn  ')
rmse_wide <- rmse_wide %>%
  select(-Level)
rownames(rmse_wide) <- rows
colnames(rmse_wide) <- 1:10

# Plot heatmap
p <- pheatmap(as.matrix(rmse_wide), cluster_rows = FALSE, cluster_cols = FALSE, 
         border_color = "white", cellwidth = 20, cellheight = 20, 
         gaps_row = seq(3, length(row_order), by = 3), # Thicker lines every 3 rows)
           main = "Variation in RMSE")  # Add title) 

# ggsave(file = 'C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\images\\1_Simulated_data\\All_results\\rmse_heatmap.png', p, width = 4, height = 4)
```

# Create accuracy heatmap
```{r}
# Convert to wide format for RMSE heatmap
acc_wide <- results_all %>%
  select(Input, Level, Correct_level) %>%
  pivot_wider(names_from = Input, values_from = Correct_level) 

# Reorder rows and columns
acc_wide <- acc_wide[match(row_order, acc_wide$Level), ]
acc_wide <- acc_wide[, c("Level", column_order), with = FALSE]

# Set row names for pheatmap
rows <- c('gplearn', 'PySR', 'feyn', 'gplearn ', 'PySR ', 'feyn ', 'gplearn  ', 'PySR  ', 'feyn  ')
acc_wide <- acc_wide %>%
  select(-Level)
rownames(acc_wide) <- rows
colnames(acc_wide) <- 1:10


# Plot heatmap
p <- pheatmap(as.matrix(acc_wide), 
              cluster_rows = FALSE, 
              cluster_cols = FALSE, 
              border_color = "white", 
              cellwidth = 20, 
              cellheight = 20, 
              gaps_row = seq(3, length(row_order), by = 3),  # Thicker lines every 3 rows
              main = 'Variation in Accuracy',
              color = colorRampPalette(c("#CCCCFF", "#6666FF", "#0000FF", "#000066"))(4)) # Light red to red color scale
ggsave(file = 'C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\images\\1_Simulated_data\\All_results\\accuracy_heatmap.png', p, width = 4, height = 4)
```

# Plot sensitivity 
```{r}
sens <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\Models\\1_Simulated_data\\pysr\\Sensitivity\\pysr_RMSE_sensitivity.csv')

# Format with correct labels
sens$Input <- factor(sens$Input, levels = c(
  "No_noise_rel_var", "No_noise_all_var", "Noise=0.25", 
  "Noise=0.5", "Noise=0.75", "Noise=1", 
  "Noise=1.25", "Noise=1.5", "Noise=1.75", 
  "Noise=2"
))
sens$Input <- as.numeric(sens$Input)
sens <- sens %>%
  mutate(Complexity = as.factor(Complexity)) %>%
  mutate(Operator = ifelse(Operator == "['myfunction(x) = x'] ['-', '+']", "Low", 
                           ifelse(Operator == "['myfunction(x) = x'] ['-', '+', '*', '/']", "Medium", "High"))) %>%
    mutate(ID = paste(Operator, "-", Input))

# Initialize a list to store plots
plot_list <- list()

# Iterate through tests and create plots
tests <- unique(sens$ID)
for(i in 1:length(tests)){
  temp <- sens %>%
    filter(ID == tests[i])
  
  # Plot
  p <- ggplot(temp, aes(x = Iteration, y = RMSE, color = Complexity)) +
    geom_point() +
    theme_classic() + 
    ggtitle(tests[i]) +
    theme(plot.title = element_text(hjust = 0.5))  # Center the title
  
  # Add plot to the list
  plot_list[[i]] <- p
}

# Extract the legend from one of the plots
legend <- get_legend(plot_list[[1]])

# Remove the legend from the individual plots
plot_list <- lapply(plot_list, function(x) x + theme(legend.position = "none"))

# Arrange plots in a grid and add a shared legend at the bottom
pdf("C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\images\\1_Simulated_data\\pysr\\sensitivity_plots.pdf", width = 11, height = 8)
plots<-ggarrange(plotlist=plot_list, ncol=3, nrow=2, common.legend = TRUE, legend="bottom")
  print(plots)
dev.off()

```


