---
title: "Plot_variable_importance"
output: html_document
date: "2024-10-15"
---
# Libraries
```{r}
library(tidyverse)
```

# Load in data
```{r}
dat <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\Albumin_runs\\Models\\3_Omic_measurements\\variable_importance.csv')
degs <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\Data_inputs\\3_Omic_measurements\\DEGs.csv') %>%
  .[,4:5]
genes <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\Albumin_runs\\Models\\3_Omic_measurements\\all_genes_in_hof.csv') 
```

# Fix gene names
```{r}
# Rewrite cleaning function from python
clean_column_values <- function(df, column_name) {
  df[[column_name]] <- sapply(df[[column_name]], function(name) {
    if (name == "S") {
      "Sulphur"
    } else if (name == "Si") {
      "Silicon"
    } else {
      cleaned_name <- gsub("\\W+", "", name) # Remove non-alphanumeric characters
      cleaned_name <- gsub("([a-zA-Z])(\\d)", "\\1_\\2", cleaned_name) # Insert underscore between letters and digits
      cleaned_name <- gsub("(\\d)([a-zA-Z])", "\\1_\\2", cleaned_name) # Insert underscore between digits and letters
      if (grepl("^[0-9]", cleaned_name)) { # Check if the name starts with a digit
        cleaned_name <- paste0("var", cleaned_name)
      }
      cleaned_name
    }
  })
  return(df)
}

# Apply to biospyder IDs
degs_clean <- clean_column_values(degs, "BioSpyder_Identifier")
colnames(degs_clean)[1] <- 'gene'

# Merge with data
dat_clean <- left_join(dat, degs_clean, by = 'gene') %>%
  select(-gene) %>%
  unique()
colnames(dat_clean)[2] <- 'gene'

# Merge with gene names for IPA
genes_clean <- left_join(genes, degs_clean) %>%
  select(Gene_Symbol) %>%
  unique()
write.csv(genes_clean, file = 'C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\Albumin_runs\\Models\\3_Omic_measurements\\all_genes_in_hof_clean.csv' )
```


# Sum directions and plot
```{r}
# Add directionality
dat_top <- dat_clean %>%
  arrange(desc(abs(var_importance))) %>%
  mutate(Association = ifelse(var_importance > 0, "Positive", "Negative"))

# Subset to top 15
dat_top <- dat_top[1:15,]

# Create bar chart
p <- ggplot(dat_top, aes(x = reorder(gene, -var_importance), y = var_importance, fill = Association)) +
  geom_bar(stat = "identity") +
  labs(x = "Gene", y = "Directional importance") +
  scale_fill_manual(values = c("Positive" = "grey", "Negative" = "black")) +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
    axis.text.y = element_text(size = 10),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  )

# Save
plot_filename <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/Albumin_runs/images/3_Omic_measurements/variable_importance_all.png')
ggsave(plot_filename, p, width = 3.5, height = 4)

```


# Check for correlations to injury protein
```{python}
import pickle
import pandas as pd

injury_df = pd.read_pickle("C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/Data_inputs/3_Omic_measurements/dat_deg")
```

```{r}
# Read in the data
data <- py$injury_df
# gene <- unique(dat_top$gene)
gene <- c('Alg11_64834', 'Cyp1a1_79654', 'Tspan4_3070', 'Csrnp1_69505', 'Slc26a4_56472', 'Arf1_31811', 'Kbtbd7_76521', 'Cyp1a1_29719', 'Art5_55361', 'Myc_30907', 'March3_58049', 'Cxcl10_29431', 'Arntl_59197', 'Dusp11_79084', 'Asb14_29409', 'Injury_Protein')


# Subset full data to important gene
dat_sub <- data[, colnames(data) %in% gene]

# Ensure all columns are numeric
dat_sub <- dat_sub %>%
  mutate(across(everything(), as.numeric))

# Initialize matrices to store p-values and correlation coefficients
cols <- colnames(dat_sub)
p_values <- matrix(0, nrow = length(cols), ncol = length(cols), dimnames = list(cols, cols))
correlation_matrix <- matrix(0, nrow = length(cols), ncol = length(cols), dimnames = list(cols, cols))

# Calculate pairwise Pearson correlations and p-values
for (i in seq_along(cols)) {
  for (j in i:length(cols)) {
    if (i != j) {
      correlation_test <- cor.test(dat_sub[[cols[i]]], dat_sub[[cols[j]]], method = "pearson")
      corr <- correlation_test$estimate
      p_value <- correlation_test$p.value
      correlation_matrix[i, j] <- corr
      correlation_matrix[j, i] <- corr
      p_values[i, j] <- p_value
      p_values[j, i] <- p_value
    } else {
      correlation_matrix[i, j] <- 1
      p_values[i, j] <- 0
    }
  }
}

# Apply FDR correction to the p-values
p_values_flat <- as.vector(p_values)
p_values_corrected <- p.adjust(p_values_flat, method = "fdr")
p_values_corrected_matrix <- matrix(p_values_corrected, nrow = length(cols), ncol = length(cols), dimnames = list(cols, cols))

# Convert correlation matrix and mask into a format suitable for ggplot
correlation_df <- melt(correlation_matrix)

# Plot heatmap where only significant correlations are colored
p <- ggplot(data = correlation_df, aes(Var1, Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", high = "red", mid = "white", midpoint = 0) +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  labs(title = NULL, fill = "Correlation")
```

# RF importance
```{r}
dat <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\Albumin_runs\\Models\\3_Omic_measurements\\rf\\rf_var_importance.csv')

# Apply to biospyder IDs
colnames(degs)[1] <- 'Feature'

# Merge with data
dat_clean <- left_join(dat, degs, by = 'Feature') %>%
  select(-Feature) %>%
  unique()
colnames(dat_clean)[2] <- 'Feature'

# Get top 15 from full
dat_full <- dat_clean %>%
  arrange(-Importance) %>%
  .[1:15,]

p <- ggplot(dat_full, aes(x = reorder(Feature, -Importance), y = Importance)) +
  geom_bar(stat = "identity") +
  labs(x = "Gene", y = "Importance") +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  ) +
  scale_y_continuous(expand = c(0, 0)) 

# Save
plot_filename <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/Albumin_runs/images/3_Omic_measurements/rf/variable_importance_all.png')
ggsave(plot_filename, p, width = 4, height = 4)
```
