---
title: "Plot_results"
output: html_document
date: "2024-09-13"
---

# Libraries
```{r}
library(tidyverse)
library(reticulate)
library(Metrics)
repl_python()
```

```{python}
import pandas as pd
import pickle
import os

# Set working directory
os.chdir(r"C:\Users\Jessie PC\OneDrive - University of North Carolina at Chapel Hill\Symbolic_regression_github\NIH_Cloud_NOSI")

# Load in data
train_y = pd.read_pickle("3_Data_intermediates/2_Chemical_measurements/Chem_train_y")
test_y = pd.read_pickle("3_Data_intermediates/2_Chemical_measurements/Chem_test_y")
train_y_pred = pd.read_pickle("3_Data_intermediates/2_Chemical_measurements/Chem_training_predictions_pysr_Full")
test_y_pred = pd.read_pickle("3_Data_intermediates/2_Chemical_measurements/Chem_test_predictions_pysr_Full")
train_y_pred_pca = pd.read_pickle("3_Data_intermediates/2_Chemical_measurements/Chem_training_predictions_pysr_PCA")
test_y_pred_pca = pd.read_pickle("3_Data_intermediates/2_Chemical_measurements/Chem_test_predictions_pysr_PCA")
train_y_pred_elastic = pd.read_pickle("3_Data_intermediates/2_Chemical_measurements/Chem_training_predictions_pysr_Elastic")
test_y_pred_elastic = pd.read_pickle("3_Data_intermediates/2_Chemical_measurements/Chem_test_predictions_pysr_Elastic")
train_y_pred_rf = pd.read_pickle("3_Data_intermediates/2_Chemical_measurements/training_predictions_rf_Full")
test_y_pred_rf = pd.read_pickle("3_Data_intermediates/2_Chemical_measurements/test_predictions_rf_Full")

# Store the inputs (Full, PCA, Elastic) in a list
input_names = ['Full', 'PCA', 'Elastic', 'RF']
train_preds_list = [train_y_pred, train_y_pred_pca, train_y_pred_elastic, train_y_pred_rf]
test_preds_list = [test_y_pred, test_y_pred_pca, test_y_pred_elastic, test_y_pred_rf]
```

# Convert to r variables clean
```{r}
# Assign the list from Python to R variables
input_names <- py$input_names
train_preds_list <- py$train_preds_list
test_preds_list <- py$test_preds_list
train_y <- py$train_y
test_y <- py$test_y

# Combine all testing data into a single DataFrame with identifiers for each dataset and input name
combined_test_dat <- do.call(rbind, lapply(seq_along(input_names), function(i) {
  input_name <- input_names[[i]]
  test_y_pred <- test_preds_list[[i]]
  
  # Combine testing data into one DataFrame with 'Actual' and 'Predicted' columns
  test_combined <- data.frame(
    Actual = test_y,
    Predicted = test_y_pred[,1]
  )
  
  
  # Calculate difference between actual and predicted
  test_df <- test_combined %>%
    mutate(Dif = Actual - Predicted)
  
  # Calculate % error
  test_df <- test_df %>%
    mutate(perc_error = (Predicted - Actual)/ Predicted * 100)
    
  
  # Extract the rownames and modify them to contain only the part before the first '_'
  Group <- gsub("_.*", "", rownames(test_df))
  
  # Add 'Group' and 'input_name' as new columns to the DataFrame
  test_df$Group <- Group
  test_df$input_name <- input_name
  
  return(test_df)
}))

# Calculate normalized RMSE
nrmse <- rmse(combined_test_dat$Actual, combined_test_dat$Predicted) / (max(combined_test_dat$Actual)- min(combined_test_dat$Actual))
```

# Plot SRA results
```{r}
# Define levels
combined_test_dat$input_name <- factor(combined_test_dat$input_name, levels = c('Full', 'PCA', 'Elastic', 'RF'))

# Clean up group labels
combined_test_dat$Group <- gsub("Smoldering", "Smold.", combined_test_dat$Group)
combined_test_dat$Group <- gsub("Flaming", "Flam.", combined_test_dat$Group)
combined_test_dat$Group <- gsub("([a-z])([A-Z])", "\\1 \\2", combined_test_dat$Group)

# Define the custom group order
custom_order <- c("Red Oak Flam.", "Pine Flam.", "Peat Flam.", 
                  "Pine Needles Smold.", "Pine Needles Flam.", 
                  "Eucalyptus Smold.", "Eucalyptus Flam.", 
                  "Red Oak Smold.", "Pine Smold.", "Peat Smold.")
custom_order <- rev(custom_order)  # Reverse the order

# Update the Group variable with the custom order
combined_test_dat$Group <- factor(combined_test_dat$Group, levels = custom_order)

# Arrange the data by 'Group' and then by 'Actual' in descending order
combined_test_dat <- combined_test_dat %>%
  arrange(desc(Group), desc(Actual))

# Update the x-axis with the reordered factor levels
combined_test_dat$rownames <- factor(rownames(combined_test_dat), levels = rownames(combined_test_dat))

# Subset
combined_test_dat <- combined_test_dat %>%
  filter(input_name == 'Full')


# Define a custom color palette for the groups
custom_colors <- c(
  "Pine Flam." = "#1b9e77",
  "Peat Flam." = "#d95f02",
  "Red Oak Smold." = "#7570b3",
  "Eucalyptus Smold." = "#e7298a",
  "Pine Needles Flam." = "#66a61e",
  "Pine Needles Smold." = "#e6ab02",
  "Red Oak Flam." = "#a6761d",
  "Eucalyptus Flam." = "#666666",
  "Pine Smold." = "#1f78b4",
  "Peat Smold." = "#b2df8a"
)

# Set up the box plot using facet_wrap for each input_name
p <- ggplot(combined_test_dat, aes(x = Group, y = Dif, fill = Group)) +
  geom_boxplot() +
  geom_point(position = position_jitter(width = 0.2), alpha = 0.5) +
  labs(x = "Group", y = "Actual - Predicted (mg/mL)") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  ) +
  scale_fill_manual(values = custom_colors) +  # Apply the custom color palette
  guides(fill = guide_legend(nrow = 3, byrow = TRUE)) +  # Adjust legend to have three rows
  facet_wrap(~ input_name, scales = "free_x")

# Print the combined plot
print(p)
# Save
plot_filename <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/5_Plots/2_Chemical_measurements/pysr/Prediction_spread_all.png')
# ggsave(plot_filename, p, width = 7, height = 4)

# Set up the bar plot using facet_wrap for each input_name, using Individual_ID as the x-axis
p_bar <- ggplot(combined_test_dat, aes(x = combined_test_dat$rownames, y = Actual, fill = Group)) +
  geom_bar(stat = "identity", alpha = 0.7) +  # Bars for 'Actual'
  geom_point(aes(y = Predicted), color = "red", size = 3, shape = 95) +  # Red dash for 'Predicted'
  labs(x = "Individual", y = "Measured Injury Protein (ng/mL)") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 14),
    legend.position = "bottom"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = custom_colors) +  # Apply the custom color palette
  facet_wrap(~ input_name, scales = "free_x") +
  guides(fill = guide_legend(nrow = 3, byrow = TRUE))  # Adjust legend to have three rows
plot_filename <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/5_Plots/2_Chemical_measurements/pysr/Prediction_vs_actual_all.png')
# ggsave(plot_filename, p_bar, width = 7, height = 4)

# Set up the bar plot using facet_wrap for each input_name, using Individual_ID as the x-axis
p_bar_two <- ggplot(combined_test_dat, aes(x = combined_test_dat$rownames, y = perc_error, fill = Group)) +
  geom_bar(stat = "identity", alpha = 0.7) +  # Bars for 'Actual'
  labs(x = "Individual", y = "Percent error") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 14),
    legend.position = "bottom"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = custom_colors) +  # Apply the custom color palette
  facet_wrap(~ input_name, scales = "free_x") +
  guides(fill = guide_legend(nrow = 3, byrow = TRUE))  # Adjust legend to have three rows
# Save the plot
plot_filename_scatter <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/5_Plots/2_Chemical_measurements/pysr/Actual_vs_Predicted_difference.png')
# ggsave(plot_filename_scatter, p_bar_two, width = 7, height = 4)

```


# Sensitivity analysis
```{r}
# Load in data
sens_full <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\4_Model_results\\2_Chemical_measurements\\pysr\\pysr_RMSE_sensitivity_Full.csv')
sens_pca <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\4_Model_results\\2_Chemical_measurements\\pysr\\pysr_RMSE_sensitivity_PCA.csv')
sens_elastic <- sens_full <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\4_Model_results\\2_Chemical_measurements\\pysr\\pysr_RMSE_sensitivity_elastic.csv')

# Put in list
dat_list <- list(sens_full, sens_pca, sens_elastic)
names(dat_list) <- c('Full', 'PCA', 'Elastic net')

# Combine and add a column for the dataset name
dat_all <- bind_rows(
  lapply(names(dat_list), function(name) {
    dat_list[[name]] %>%
      mutate(Dataset = name)
  })
)

# Make complexity a factor
dat_all$Complexity <- as.factor(dat_all$Complexity)

# Iterate through tests and create plots
tests <- unique(dat_all$Dataset)
for(i in 1:length(tests)){
  temp <- dat_all %>%
    filter(Dataset == tests[i])
  
  # Plot
  p <- ggplot(temp, aes(x = Iteration, y = log(RMSE), color = Complexity)) +
    geom_point() +
    theme_classic() + 
    ggtitle(tests[i]) +
    theme(plot.title = element_text(hjust = 0.5)) + 
    # theme(legend.position="bottom") + 
    guides(color = guide_legend(ncol = 2)) +
    theme(
      axis.text.x = element_text(size = 14), 
      axis.text.y = element_text(size = 14), 
      axis.title.x = element_text(size = 16, face = "bold"),
      axis.title.y = element_text(size =16, face = "bold")
    )
  
  # Save
  plot_filename <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/5_Plots/2_Chemical_measurements/pysr/sensitivity', tests[i], '.png')
  ggsave(plot_filename, p, width = 8, height = 4)
}


```

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
# Variable importance
# Libraries
```{r}
library(tidyverse)
library(reticulate)
library(tidytext)
library(gridExtra)
```

# Load in data
```{r}
# Load in summed importance values
dat_full <- read.csv('..\\..\\4_Model_results\\2_Chemical_measurements\\pysr\\variable_importance_Full.csv')
dat_pca <- read.csv('..\\..\\4_Model_results\\2_Chemical_measurements\\pysr\\variable_importance_PCA.csv')
dat_elastic <- read.csv('..\\..\\4_Model_results\\2_Chemical_measurements\\pysr\\variable_importance_Elastic.csv')

# Put in list
dat_list <- list(dat_full, dat_pca, dat_elastic)

# Load in full importance values
dat_all_full <- read.csv('..\\..\\4_Model_results\\2_Chemical_measurements\\pysr\\partial_deriv_Full.csv')
dat_all_pca <- read.csv('..\\..\\4_Model_results\\2_Chemical_measurements\\pysr\\partial_deriv_PCA.csv')
dat_all_elastic <- read.csv('..\\..\\4_Model_results\\2_Chemical_measurements\\pysr\\partial_deriv_Elastic.csv')

# Load in chemical categories
class <- read.csv('..\\..\\1_Data_inputs\\2_Chemical_measurements\\Chemical_categories.csv')

# Put in list
dat_all_list <- list(dat_all_full, dat_all_pca, dat_all_elastic)
names(dat_all_list) <- c("Full", "PCA", "Elastic")
```

# Fix names
```{r}
clean_column_values <- function(column) {
  # Apply cleaning logic to each element in the column
  sapply(column, function(value) {
    if (value == "S") {
      return("Sulphur")
    } else if (value == "Si") {
      return("Silicon")
    } else {
      # Remove non-alphanumeric characters
      cleaned_value <- gsub("\\W+", "", value)
      # Add underscores between letters and numbers
      cleaned_value <- gsub("([a-zA-Z])(\\d)", "\\1_\\2", cleaned_value)
      cleaned_value <- gsub("(\\d)([a-zA-Z])", "\\1_\\2", cleaned_value)
      # Add prefix if the value starts with a digit
      if (grepl("^[0-9]", cleaned_value)) {
        cleaned_value <- paste0("var", cleaned_value)
      }
      return(cleaned_value)
    }
  })
}

# Apply to the 'Chemical' column
class <- class %>%
  mutate(chem = clean_column_values(Chemical))
```

# Bar chart of detections
```{r}
# Count instances
class_count <- table(class$Chemical.Category) %>%
  as.data.frame()

new_palette <- c(
  "Inorganics" = "#f7a258",      # Soft orange
  "Methoxyphenols" = "#8dd3c7",  # Light teal
  "PAHs" = "#ff9dae",            # Soft pink
  "Ions" = "#bebada",            # Pale purple
  "n-Alkanes" = "#fb8072",
  'Levoglucosan' = '#7F7F7F'
)

p <- ggplot(class_count, aes(x = reorder(Var1, -Freq), y = Freq, fill = Var1)) +
  geom_bar(stat = "identity") +
  labs(x = "Chemical class", y = "Chemicals targeted") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Removes the x-axis labels
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold"),
    legend.title = element_text(size = 16, face = "bold"),
    legend.text = element_text(size = 14),
    legend.position = "bottom"
  ) +
  # facet_grid(. ~ Dataset, scales = "free_x", space = "free") +
  scale_x_reordered() +  # Handles the reordered factors
  scale_y_continuous(expand = c(0, 0)) +  # This removes the padding between bars and the x-axis
  scale_fill_manual(values = new_palette) +
  guides(fill = guide_legend(title = "Chemical Class", nrow = 2))
```



# Sum directions and plot
```{r}
# Names for the datasets
dataset_names <- c("Full", "PCA", "Elastic")

# Combine all data into a single DataFrame with an identifier for each dataset
combined_dat <- do.call(rbind, lapply(1:length(dat_list), function(i) {
  dat <- dat_list[[i]]
  
  dat_top <- dat %>%
    mutate(var_importance = var_importance / uniq_instances) %>%
    # mutate(var_importance = var_importance / max(abs(var_importance))) %>%
    arrange(desc(abs(var_importance))) %>%
    mutate(Association = ifelse(var_importance > 0, "Positive", "Negative"))

  
  # Subset only the top 15 for the first dataset
  if (i == 1) {
    dat_top <- dat_top[1:15, ]
  }

  # Add a column indicating the dataset name
  dat_top$dataset <- dataset_names[i]
  return(dat_top)
}))

# Clean up names for combined_dat
combined_dat <- left_join(combined_dat, class, by = 'chem') 
combined_dat <- combined_dat %>%
  mutate(Chemical = ifelse(is.na(Chemical), chem, Chemical)) %>%
  select(-chem)

# Set order
combined_dat$dataset <- factor(combined_dat$dataset, levels = c('Full', 'PCA', 'Elastic'))

# Subset 
combined_dat <- combined_dat %>%
  filter(dataset == 'Full')


p <- ggplot(combined_dat, aes(x = reorder_within(Chemical, -var_importance, dataset), y = var_importance, fill = Association)) +
  geom_bar(stat = "identity") +
  labs(x = "Chemical", y = "Directional importance") +
  scale_fill_manual(values = c("Positive" = "grey", "Negative" = "black")) +
  scale_x_reordered() +  # Add this line to clean up x-axis labels
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  ) 


# Print the combined plot
print(p)

# Save
plot_filename <- paste0('..\\..\\5_Plots/2_Chemical_measurements/pysr/variable_importance_avg.png')
ggsave(plot_filename, p, width = 4, height = 4)
```

# by chemical class
```{r}
# Names for the datasets
dataset_names <- c("Full", "PCA", "Elastic")

# Combine all data into a single DataFrame with an identifier for each dataset
combined_dat <- do.call(rbind, lapply(1:length(dat_list), function(i) {
  dat <- dat_list[[i]]
  
  dat_top <- dat %>%
    arrange(desc(abs(var_importance))) %>%
    mutate(Association = ifelse(var_importance > 0, "Positive", "Negative"))

  # Add a column indicating the dataset name
  dat_top$dataset <- dataset_names[i]
  return(dat_top)
}))

# Clean up names for combined_dat
combined_dat <- left_join(combined_dat, class, by = 'chem') 
combined_dat <- combined_dat %>%
  mutate(Chemical = ifelse(is.na(Chemical), chem, Chemical)) %>%
  select(-chem)

# Set order
combined_dat$dataset <- factor(combined_dat$dataset, levels = c('Full', 'PCA', 'Elastic'))

# # Subset for presentation 
combined_dat <- combined_dat %>%
  filter(dataset == 'Full') %>%
  group_by(Chemical.Category) %>%
  mutate(Class_imp = sum(var_importance)) %>%
  select(Chemical.Category, Class_imp) %>%
  unique() %>%
  mutate(Association = ifelse(Class_imp > 0, 'Positive', 'Negative'))

# Plot
p <- ggplot(combined_dat, aes(x = reorder(Chemical.Category, -Class_imp), y = Class_imp, fill = Association)) +
  geom_bar(stat = "identity") +
  labs(x = "Chemical", y = "Directional importance") +
  scale_fill_manual(values = c("Positive" = "grey", "Negative" = "black")) +
  scale_x_reordered() +  # Add this line to clean up x-axis labels
  theme_classic() +
  theme(
      axis.text.x = element_text(size = 14, angle = 45, hjust = 1), 
      axis.text.y = element_text(size = 14), 
      axis.title.x = element_text(size = 16, face = "bold"),
      axis.title.y = element_text(size =16, face = "bold"), 
      legend.position = "bottom"
    ) 

```

# Importance distribution 
```{r}

# Initialize an empty list to store the plots
plots_list <- list()

# Iterate through lists
for(i in 1:length(dat_all_list)){
  
  # Subset data
  dat <- dat_all_list[[i]] %>%
    unique()
  
  # Get unique chemicals
  vars <- unique(dat$chem)
  
  # Initialize a list for plots in this iteration
  iteration_plots <- list()
  
  # Iterate through variables
  for(j in 1:length(vars)){
    
    # Subset to relevant chem
    temp <- dat %>% 
      filter(chem == vars[j])
    
    # Create histogram plot
    p <- ggplot(temp, aes(x = integrated_derivative)) +
      geom_histogram(binwidth = 1, color = "black", fill = "blue") +
      labs(title = paste0(vars[j], " (n=", nrow(temp), ")"),  
           x = "Variable Importance", 
           y = "Frequency") +
      theme_minimal() +
      theme(plot.title = element_text(hjust = 0.5)) # Center title
    
    # Append the plot to the iteration list
    iteration_plots[[j]] <- p
  }
  
  # Define the dimensions for wider pages
  pdf_width <- 14  # Set to a wider width
  pdf_height <- 8  # Adjust height as needed
  
  # Export the plots to a PDF with 6 plots per page (3 columns x 2 rows)
  pdf(paste0("..\\..\\5_Plots/2_Chemical_measurements/pysr/variable_importance_distribution_uniq_", names(dat_all_list)[i], ".pdf"),
      width = pdf_width, height = pdf_height)
  
  # Split the plots into groups of 6
  plot_groups <- split(iteration_plots, ceiling(seq_along(iteration_plots) / 6))
  
  # Loop through each group of 6 plots
  for (group in plot_groups) {
    # Arrange the plots into a 3x2 grid
    grid <- marrangeGrob(group, ncol = 3, nrow = 2)
    # Print the grid to the PDF
    print(grid)
  }
  
  # Close the PDF device
  dev.off()
}
```

# Train-test RMSE
```{r}
df <- read.csv('..\\..\\3_Data_intermediates\\2_Chemical_measurements\\Chem_rmse_values_pysr_Full.csv')

# Reshape the data to long format
df_long <- df %>%
  pivot_longer(cols = c(Train.RMSE, Test.RMSE), 
               names_to = "Type", 
               values_to = "RMSE") %>%
  filter(HOF.equation > 2)


# Create the plot
p <- ggplot(df_long, aes(x = HOF.equation, y = RMSE, color = Type, group = Type)) +
  geom_line(size = 1.2) + 
  geom_point(size = 3) +
  scale_color_manual(values = c("Train.RMSE" = "#1f77b4", "Test.RMSE" = "#ff7f0e")) + # Better colors
  theme_classic() +
  labs(
    x = "HOF Equation",
    y = "RMSE",
    color = "Type"
  ) +
  theme(
    axis.text.x = element_text(size = 10, angle = 0, hjust = 1),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  ) +
  scale_x_discrete(limits = unique(df_long$HOF.equation)) # Ensure all x-axis ticks are labeled

# Save
plot_filename <- paste0('..\\..\\5_Plots/2_Chemical_measurements/pysr/RMSE_by_HOF.png')
ggsave(plot_filename, p, width = 4, height = 4)
```


# RF importance
```{r}
dat_full <- read.csv('..\\..\\4_Model_results\\2_Chemical_measurements\\rf\\rf_var_importance_Full.csv')
dat_pca <- read.csv('..\\..\\4_Model_results\\2_Chemical_measurements\\rf\\rf_var_importance_PCA.csv')
dat_elastic <- read.csv('..\\..\\4_Model_results\\2_Chemical_measurements\\rf\\rf_var_importance_Elastic.csv')

# Get top 15 from full
dat_full <- dat_full %>%
  arrange(-Importance) %>%
  .[1:15,]

# Put in list
dat_list <- list(dat_full, dat_pca, dat_elastic)
names(dat_list) <- c('Full', 'PCA', 'Elastic net')

# Combine and add a column for the dataset name
dat_all <- bind_rows(
  lapply(names(dat_list), function(name) {
    dat_list[[name]] %>%
      mutate(Dataset = name)
  })
)

# Set order
dat_all$Dataset <- factor(dat_all$Dataset, levels = c('Full', 'PCA', 'Elastic net'))

# Add classifications 
colnames(class)[2] <- 'Feature'
dat_all <- dat_all %>%
  left_join(., class, by = 'Feature') %>%
  filter(Dataset == 'Full')

new_palette <- c(
  "Inorganics" = "#f7a258",      # Soft orange
  "Methoxyphenols" = "#8dd3c7",  # Light teal
  "PAHs" = "#ff9dae",            # Soft pink
  "Ions" = "#bebada",            # Pale purple
  "n-Alkanes" = "#fb8072"        # Coral
)
p <- ggplot(dat_all, aes(x = reorder_within(Feature, -Importance, Dataset), y = Importance, fill = Chemical.Category)) +
  geom_bar(stat = "identity") +
  labs(x = "Chem", y = "Importance (MDI)") +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 14, angle = 45, hjust = 1),
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold"),
    legend.title = element_text(size = 16, face = "bold"),
    legend.text = element_text(size = 14),
    legend.position = "bottom"
  ) +
  # facet_grid(. ~ Dataset, scales = "free_x", space = "free") +
  scale_x_reordered() +  # Handles the reordered factors
  scale_y_continuous(expand = c(0, 0)) +  # This removes the padding between bars and the x-axis
  labs(x = 'Chemical') + 
  scale_fill_manual(values = new_palette) +
  guides(fill=guide_legend(title="Chemical Class"))

# Save
plot_filename <- paste0('C:/Users/jrchapp3/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/5_Plots/2_Chemical_measurements/rf/variable_importance_all.png')
ggsave(plot_filename, p, width = 7, height = 4)
```

