---
title: "Plot_results"
output: html_document
date: "2024-09-13"
---

# Libraries
```{r}
library(tidyverse)
library(reticulate)
repl_python()
```

```{python}
import pandas as pd
import pickle
import os

# Set working directory
os.chdir(r"C:\Users\jrchapp3\OneDrive - University of North Carolina at Chapel Hill\Symbolic_regression_github\NIH_Cloud_NOSI")

# Load in data
train_y = pd.read_pickle("3_Data_intermediates/3_Omic_measurements/Omic_train_y")
test_y = pd.read_pickle("3_Data_intermediates/3_Omic_measurements/Omic_test_y")
train_y_pred = pd.read_pickle("3_Data_intermediates/3_Omic_measurements/Omic_training_predictions_pysr_Full")
test_y_pred = pd.read_pickle("3_Data_intermediates/3_Omic_measurements/Omic_test_predictions_pysr_Full")
train_y_pred_pca = pd.read_pickle("3_Data_intermediates/3_Omic_measurements/Omic_training_predictions_pysr_PCA")
test_y_pred_pca = pd.read_pickle("3_Data_intermediates/3_Omic_measurements/Omic_test_predictions_pysr_PCA")
train_y_pred_elastic = pd.read_pickle("3_Data_intermediates/3_Omic_measurements/Omic_training_predictions_pysr_Elastic")
test_y_pred_elastic = pd.read_pickle("3_Data_intermediates/3_Omic_measurements/Omic_test_predictions_pysr_Elastic")
train_y_pred_rf = pd.read_pickle("3_Data_intermediates/3_Omic_measurements/training_predictions_rf_Full")
test_y_pred_rf = pd.read_pickle("3_Data_intermediates/3_Omic_measurements/test_predictions_rf_Full")

# Store the inputs (Full, PCA, Elastic) in a list
input_names = ['Full', 'PCA', 'Elastic', 'RF']
train_preds_list = [train_y_pred, train_y_pred_pca, train_y_pred_elastic, train_y_pred_rf]
test_preds_list = [test_y_pred, test_y_pred_pca, test_y_pred_elastic, test_y_pred_rf]
```

# Convert to r variables and format
```{r}
train_y <- py$train_y
test_y <- py$test_y
train_y_pred <- py$train_y_pred
test_y_pred <- py$test_y_pred
test_preds_list <- py$test_preds_list

# Combine testing data into one DataFrame with 'Actual' and 'Predicted' columns
test_combined <- data.frame(
  Predicted = test_preds_list[[3]][9, 'Predictions'][[1]],
  Actual = test_y
)

# Combine training data into one DataFrame with 'Actual' and 'Predicted' columns
train_combined <- data.frame(
  Actual = train_y,
  Predicted = train_y_pred[,1]
)

```

# Plot testing data
```{r}
# Calculate difference between actual and predicted
test_df <- test_combined %>%
  mutate(Dif = Actual - Predicted)

# Calculate normalized RMSE
nrmse <- rmse(test_df$Actual, test_df$Predicted) / (max(test_df$Actual)- min(test_df$Actual))

# Extract the rownames and modify them to contain only the part before the first '_'
Group <- gsub("_.*", "", rownames(test_df))

# Add 'Group' as a new column to your dataframe
test_df$Group <- Group

# Clean up group labels
test_df$Group <- gsub("Smoldering", "Smold.", test_df$Group)
test_df$Group <- gsub("Flaming", "Flam.", test_df$Group)
test_df$Group <- gsub("([a-z])([A-Z])", "\\1 \\2", test_df$Group)

# Define the custom group order
custom_order <- c("Red Oak Flam.", "Pine Flam.", "Peat Flam.", "Pine Needles Flam.", "Pine Needles Smold.", "Eucalyptus Smold.", "Eucalyptus Flam.", "Red Oak Smold.", "Pine Smold.", "Peat Smold.")
  
custom_order <- rev(custom_order)  # Reverse the order

# Update the Group variable with the custom order
test_df$Group <- factor(test_df$Group, levels = custom_order)

# Arrange the data by 'Group' and then by 'Actual' in descending order
test_df <- test_df %>%
  arrange(desc(Group), desc(Actual))

# Update the x-axis with the reordered factor levels
test_df$rownames <- factor(rownames(test_df), levels = rownames(test_df))


# Define a custom color palette for the groups
custom_colors <- c(
  "Pine Flam." = "#1b9e77",
  "Peat Flam." = "#d95f02",
  "Red Oak Smold." = "#7570b3",
  "Eucalyptus Smold." = "#e7298a",
  "Pine Needles Flam." = "#66a61e",
  "Pine Needles Smold." = "#e6ab02",
  "Red Oak Flam." = "#a6761d",
  "Eucalyptus Flam." = "#666666",
  "Pine Smold." = "#1f78b4",
  "Peat Smold." = "#b2df8a"
)

# Plot
p <- ggplot(test_df, aes(x = Group, y = Dif, fill = Group)) +
  geom_boxplot() +
  geom_point(position = position_jitter(width = 0.2), alpha = 0.5) +
    labs(x = "Group", y = "Actual - Predicted (ng/mL)") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  ) +
  scale_fill_manual(values = custom_colors) +
  guides(fill = guide_legend(nrow = 3, byrow = TRUE))   # Adjust legend to have three rows

# ggsave('C:/Users/jrchapp3/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/3_Omic_measurements/prediction_spread.png',p, width = 7, height = 4)

# Set up the bar plot using facet_wrap for each input_name, using Individual_ID as the x-axis
p_bar <- ggplot(test_df, aes(x = test_df$rownames, y = Actual, fill = Group)) +
  geom_bar(stat = "identity", alpha = 0.7) +  # Bars for 'Actual'
  geom_point(aes(y = Predicted), color = "red", size = 5, shape = 95) +  # Red dash for 'Predicted'
  labs(x = "Individual", y = "Measured Injury Protein (mg/mL)") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 8),
    legend.position = "bottom"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = custom_colors) +  # Apply the custom color palette
  guides(fill = guide_legend(nrow = 4, byrow = TRUE))  # Adjust legend to have three rows
plot_filename <- paste0('C:/Users/jrchapp3/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/5_Plots/3_Omic_measurements/Prediction_vs_actual_all.png')
ggsave(plot_filename, p_bar, width = 4, height = 4)

# Set up the bar plot using facet_wrap for each input_name, using Individual_ID as the x-axis
p_bar_two <- ggplot(test_df, aes(x = test_df$rownames, y = Dif, fill = Group)) +
  geom_bar(stat = "identity", alpha = 0.7) +  # Bars for 'Actual'
  labs(x = "Individual", y = "Actual - Predicted (ng/mL)") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = custom_colors) +  # Apply the custom color palette
  guides(fill = guide_legend(nrow = 3, byrow = TRUE))  # Adjust legend to have three rows
# Save the plot
plot_filename_scatter <- paste0('C:/Users/jrchapp3/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/3_Omic_measurements/Actual_vs_Predicted_difference.png')
ggsave(plot_filename_scatter, p_bar_two, width = 7, height = 4)


```

# Sensitivity Analysis
```{r}
# Load in data
dat <- read.csv('..\\..\\4_Model_results\\3_Omic_measurements\\pysr_RMSE_sensitivity.csv')

# convert complexity to factor
dat$Complexity <- as.factor(dat$Complexity)

# Plot
p <- ggplot(dat, aes(x = Iteration, y = log(RMSE), color = Complexity)) +
  geom_point() +
  theme_classic() + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(legend.position = "none") +
  theme(
    axis.text.x = element_text(size = 14),  
    axis.text.y = element_text(size = 14),  
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold")
  ) +
  guides(color = guide_legend(nrow = 2)) 

# Save
plot_filename <- paste0('C:/Users/jrchapp3/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/3_Omic_measurements/sensitivity.png')
  ggsave(plot_filename, p, width = 4, height = 4)
```

# Plot pathways
```{r}
top_diseases <- read.table('C://Users//jrchapp3//OneDrive - University of North Carolina at Chapel Hill//Symbolic_regression_github//NIH_Cloud_NOSI//Data_inputs//3_Omic_measurements//top_diseases.txt', header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# Function to extract the minimum p-value from the p.value string
extract_min_pval <- function(pvalue_str) {
  # Split on hyphens not preceded by 'E'
  pval_parts <- strsplit(pvalue_str, "(?<!E)-", perl = TRUE)[[1]]
  # Remove any whitespace
  pval_parts <- trimws(pval_parts)
  # Convert to numeric
  pvals <- as.numeric(pval_parts)
  # Take the minimum value
  min_pval <- min(pvals, na.rm = TRUE)
  return(min_pval)
}

# Apply the function to the p.value column
top_diseases <- top_diseases %>%
  mutate(
    p_min = sapply(p.value, extract_min_pval),
    p_transformed = -log10(p_min)  # Transform p-values to -log10 scale
  )

# Subset the top 15 rows by p.value
top_15_diseases <- top_diseases %>%
  arrange(p.value) %>%
  slice(1:15)

# Subset the top 15 rows by the smallest p-value
top_15_diseases <- top_diseases %>%
  arrange(p_min) %>%
  slice(1:15)

# Create the bar chart
p <- ggplot(top_15_diseases, aes(x = reorder(Category, p_transformed), y = p_transformed)) +
  geom_bar(stat = "identity") +
  coord_flip() +  # Flip coordinates for better readability
  labs(
    x = NULL,  # Remove the 'Category' label
    y = "-log10(p-value)",
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold")
  ) +
  scale_y_continuous(expand = c(0, 0))  

# Read the data
top_pathways <- read.table(
  'C://Users//jrchapp3//OneDrive - University of North Carolina at Chapel Hill//Symbolic_regression_github//NIH_Cloud_NOSI//Data_inputs//3_Omic_measurements//top_pathways.txt',
  header = TRUE, sep = "\t", stringsAsFactors = FALSE
)
colnames(top_pathways)[2] <- 'p_transformed'

# Subset the top 15 pathways by the smallest p-value
top_15_pathways <- top_pathways %>%
  arrange(-p_transformed) %>%
  slice(1:15)

# Create the bar chart with adjustments
p <- ggplot(top_15_pathways, aes(x = reorder(Ingenuity.Canonical.Pathways, p_transformed), y = p_transformed)) +
  geom_bar(stat = "identity") +
  coord_flip() +  # Flip coordinates for better readability
  labs(
    x = NULL,  # Remove the 'Category' label
    y = "-log10(p-value)",
    title = "Top 15 Pathways by p-value"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold")
  ) +
  scale_y_continuous(expand = c(0, 0))  # Remove padding to make bars touch x-axi

```

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ 
# Variable importance
# Libraries
```{r}
library(tidyverse)
library(reticulate)
library(tidytext)
library(gridExtra)
```

# Load in data
```{r}
# Load in summed importance values
dat_DEG <- read.csv('..\\..\\4_Model_results\\3_Omic_measurements\\pysr\\variable_importance_DEG.csv')
dat_pca <- read.csv('..\\..\\4_Model_results\\3_Omic_measurements\\pysr\\variable_importance_PCA.csv')
dat_elastic <- read.csv('..\\..\\4_Model_results\\3_Omic_measurements\\pysr\\variable_importance_Elastic.csv')

# Put in list
dat_list <- list(dat_DEG, dat_pca, dat_elastic)
names(dat_list) <- c("DEG", "PCA", "Elastic")

# Load in full importance values
dat_all_DEG <- read.csv('..\\..\\4_Model_results\\3_Omic_measurements\\pysr\\partial_deriv_DEG.csv')
dat_all_pca <- read.csv('..\\..\\4_Model_results\\3_Omic_measurements\\pysr\\partial_deriv_PCA.csv')
dat_all_elastic <- read.csv('..\\..\\4_Model_results\\3_Omic_measurements\\pysr\\partial_deriv_Elastic.csv')

# Put in list
dat_all_list <- list(dat_all_DEG, dat_all_pca, dat_all_elastic)
names(dat_all_list) <- c("DEG", "PCA", "Elastic")


# read in gene names
degs <- read.csv('..\\..\\1_Data_inputs\\3_Omic_measurements\\DEGs.csv') %>%
  .[,4:5]
genes <- read.csv('..\\..\\4_Model_results\\3_Omic_measurements\\all_genes_in_hof.csv') 
```

# Fix gene names
```{r}
# Rewrite cleaning function from python
clean_column_values <- function(df, column_name) {
  df[[column_name]] <- sapply(df[[column_name]], function(name) {
    if (name == "S") {
      "Sulphur"
    } else if (name == "Si") {
      "Silicon"
    } else {
      cleaned_name <- gsub("\\W+", "", name) # Remove non-alphanumeric characters
      cleaned_name <- gsub("([a-zA-Z])(\\d)", "\\1_\\2", cleaned_name) # Insert underscore between letters and digits
      cleaned_name <- gsub("(\\d)([a-zA-Z])", "\\1_\\2", cleaned_name) # Insert underscore between digits and letters
      if (grepl("^[0-9]", cleaned_name)) { # Check if the name starts with a digit
        cleaned_name <- paste0("var", cleaned_name)
      }
      cleaned_name
    }
  })
  return(df)
}

# Apply to biospyder IDs
degs_clean <- clean_column_values(degs, "BioSpyder_Identifier")
colnames(degs_clean)[1] <- 'gene'

# Clean names in dat_list
colnames(dat_list[[1]])[1] <- 'gene'
colnames(dat_list[[3]])[1] <- 'gene'
colnames(dat_list[[2]])[1] <- 'Gene_Symbol'
dat_list[[1]] <- left_join(dat_list[[1]], degs_clean, by = 'gene') %>%
  select(-gene) %>%
  unique()
dat_list[[3]] <- left_join(dat_list[[3]], degs_clean, by = 'gene') %>%
  select(-gene) %>%
  unique()

# Merge with gene names for IPA
genes_clean <- left_join(genes, degs_clean) %>%
  select(Gene_Symbol) %>%
  unique()
#write.csv(genes_clean, file = '..\\..\\4_Model_results\\3_Omic_measurements\\all_genes_in_hof_clean.csv' )
```


# Sum directions and plot
```{r}
# Names for the datasets
dataset_names <- c("DEG", "PCA", "Elastic")

# Combine all data into a single DataFrame with an identifier for each dataset
combined_dat <- do.call(rbind, lapply(1:length(dat_list), function(i) {
  dat <- dat_list[[i]]
  
  dat_top <- dat %>%
    # mutate(var_importance = var_importance / uniq_instances) %>%
    mutate(var_importance = var_importance / max(abs(var_importance))) %>%
    arrange(desc(abs(var_importance))) %>%
    mutate(Association = ifelse(var_importance > 0, "Positive", "Negative"))

  
  # Subset only the top 15 for the first dataset
  if (i == 1 | i == 3) {
    dat_top <- dat_top[1:15, ]
  }

  # Add a column indicating the dataset name
  dat_top$dataset <- dataset_names[i]
  return(dat_top)
}))

# Set order
combined_dat$dataset <- factor(combined_dat$dataset, levels = c('DEG', 'PCA', 'Elastic'))

# Subset 
combined_dat <- combined_dat %>%
  filter(dataset == 'Elastic')

# Plot
p <- ggplot(combined_dat, aes(x = reorder_within(Gene_Symbol, -var_importance, dataset), y = var_importance, fill = Association)) +
  geom_bar(stat = "identity") +
  labs(x = "Gene Symbol", y = "Directional importance") +
  scale_fill_manual(values = c("Positive" = "grey", "Negative" = "black")) +
  scale_x_reordered() +  # Clean up x-axis labels
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 10, angle = 45, hjust = 1, face = "italic"), # Italicize x-axis labels
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 8),
    legend.position = "bottom"
  )


# Print the combined plot
print(p)

# # Save
plot_filename <- paste0('..\\..\\5_Plots\\3_Omic_measurements/variable_importance_all.png')
ggsave(plot_filename, p, width = 3.8, height = 4)

```

# Train-test RMSE
```{r}
df <- read.csv('..\\..\\3_Data_intermediates\\3_Omic_measurements\\Omic_rmse_values_pysr_Elastic.csv')

# Reshape the data to long format
df_long <- df %>%
  pivot_longer(cols = c(Train.RMSE, Test.RMSE), 
               names_to = "Type", 
               values_to = "RMSE") %>%
  filter(HOF.equation > 2)


# Create the plot
p <- ggplot(df_long, aes(x = HOF.equation, y = RMSE, color = Type, group = Type)) +
  geom_line(size = 1.2) + 
  geom_point(size = 3) +
  scale_color_manual(values = c("Train.RMSE" = "#1f77b4", "Test.RMSE" = "#ff7f0e")) + # Better colors
  theme_classic() +
  labs(
    x = "HOF Equation",
    y = "RMSE",
    color = "Type"
  ) +
  theme(
    axis.text.x = element_text(size = 10, angle = 0, hjust = 1),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  ) +
  scale_x_discrete(limits = unique(df_long$HOF.equation)) # Ensure all x-axis ticks are labeled

# Save
plot_filename <- paste0('..\\..\\5_Plots/3_Omic_measurements/pysr/RMSE_by_HOF.png')
ggsave(plot_filename, p, width = 4, height = 4)
```

# RF importance
```{r}
dat <- read.csv('..\\..\\4_Model_results\\3_Omic_measurements\\rf\\rf_var_importance.csv')

# Apply to biospyder IDs
colnames(degs)[1] <- 'Feature'

# Merge with data
dat_clean <- left_join(dat, degs, by = 'Feature') %>%
  select(-Feature) %>%
  unique()
colnames(dat_clean)[2] <- 'Feature'

# Get top 15 from full
dat_full <- dat_clean %>%
  arrange(-Importance) %>%
  .[1:15,]

# Plot
p <- ggplot(dat_full, aes(x = reorder(Feature, -Importance), y = Importance)) +
  geom_bar(stat = "identity") +
  labs(x = "Gene", y = "Importance") +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 10, angle = 45, hjust = 1),
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title = element_text(size = 12, face = "bold"),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  ) +
  scale_y_continuous(expand = c(0, 0)) 
# Save
plot_filename <- paste0('C:/Users/jrchapp3/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/3_Omic_measurements/rf/variable_importance_all.png')
ggsave(plot_filename, p, width = 4, height = 4)
```
 