---
title: "Plot_results"
output: html_document
date: "2024-09-13"
---

# Libraries
```{r}
library(tidyverse)
library(reticulate)
repl_python()
```

```{python}
import pandas as pd
import pickle
import os

# Set working directory
os.chdir(r"C:\Users\Jessie PC\OneDrive - University of North Carolina at Chapel Hill\Symbolic_regression_github\NIH_Cloud_NOSI")

# Load in data
train_y = pd.read_pickle("Data_inputs/3_Omic_measurements/train_y")
test_y = pd.read_pickle("Data_inputs/3_Omic_measurements/test_y")
train_y_pred = pd.read_pickle("Data_inputs/3_Omic_measurements/training_predictions")
test_y_pred = pd.read_pickle("Data_inputs/3_Omic_measurements/test_predictions")
```

# Convert to r variables and format
```{r}
train_y <- py$train_y
test_y <- py$test_y
train_y_pred <- py$train_y_pred
test_y_pred <- py$test_y_pred

# Combine training data into one DataFrame with 'Actual' and 'Predicted' columns
train_combined <- data.frame(
  Actual = train_y,
  Predicted = train_y_pred[,1]
)

# Combine testing data into one DataFrame with 'Actual' and 'Predicted' columns
test_combined <- data.frame(
  Actual = test_y,
  Predicted = test_y_pred[,1]
)
```

# Plot testing data
```{r}
# Calculate difference between actual and predicted
test_df <- test_combined %>%
  mutate(Dif = Actual - Predicted)

# Calculate normalized RMSE
nrmse <- rmse(test_df$Actual, test_df$Predicted) / (max(test_df$Actual)- min(test_df$Actual))

# Extract the rownames and modify them to contain only the part before the first '_'
Group <- gsub("_.*", "", rownames(test_df))

# Add 'Group' as a new column to your dataframe
test_df$Group <- Group

# Clean up group labels
test_df$Group <- gsub("Smoldering", "Smold.", test_df$Group)
test_df$Group <- gsub("Flaming", "Flam.", test_df$Group)
test_df$Group <- gsub("([a-z])([A-Z])", "\\1 \\2", test_df$Group)

# Define the custom group order
custom_order <- c("Red Oak Flam.", "Pine Flam.", "Peat Flam.", "Pine Needles Flam.", "Pine Needles Smold.", "Eucalyptus Smold.", "Eucalyptus Flam.", "Red Oak Smold.", "Pine Smold.", "Peat Smold.")
  
custom_order <- rev(custom_order)  # Reverse the order

# Update the Group variable with the custom order
test_df$Group <- factor(test_df$Group, levels = custom_order)

# Arrange the data by 'Group' and then by 'Actual' in descending order
test_df <- test_df %>%
  arrange(desc(Group), desc(Actual))

# Update the x-axis with the reordered factor levels
test_df$rownames <- factor(rownames(test_df), levels = rownames(test_df))


# Define a custom color palette for the groups
custom_colors <- c(
  "Pine Flam." = "#1b9e77",
  "Peat Flam." = "#d95f02",
  "Red Oak Smold." = "#7570b3",
  "Eucalyptus Smold." = "#e7298a",
  "Pine Needles Flam." = "#66a61e",
  "Pine Needles Smold." = "#e6ab02",
  "Red Oak Flam." = "#a6761d",
  "Eucalyptus Flam." = "#666666",
  "Pine Smold." = "#1f78b4",
  "Peat Smold." = "#b2df8a"
)

# Plot
p <- ggplot(test_df, aes(x = Group, y = Dif, fill = Group)) +
  geom_boxplot() +
  geom_point(position = position_jitter(width = 0.2), alpha = 0.5) +
    labs(x = "Group", y = "Actual - Predicted (ng/mL)") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  ) +
  scale_fill_manual(values = custom_colors) +
  guides(fill = guide_legend(nrow = 3, byrow = TRUE))   # Adjust legend to have three rows

ggsave('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/3_Omic_measurements/prediction_spread.png',p, width = 7, height = 4)

# Set up the bar plot using facet_wrap for each input_name, using Individual_ID as the x-axis
p_bar <- ggplot(test_df, aes(x = test_df$rownames, y = Actual, fill = Group)) +
  geom_bar(stat = "identity", alpha = 0.7) +  # Bars for 'Actual'
  geom_point(aes(y = Predicted), color = "red", size = 3, shape = 95) +  # Red dash for 'Predicted'
  labs(x = "Individual", y = "Measured Injury Protein (ng/mL)") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 14),
    legend.position = "bottom"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = custom_colors) +  # Apply the custom color palette
  guides(fill = guide_legend(nrow = 4, byrow = TRUE))  # Adjust legend to have three rows
plot_filename <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/3_Omic_measurements/Prediction_vs_actual_all.png')
ggsave(plot_filename, p_bar, width = 7, height = 4)

# Set up the bar plot using facet_wrap for each input_name, using Individual_ID as the x-axis
p_bar_two <- ggplot(test_df, aes(x = test_df$rownames, y = Dif, fill = Group)) +
  geom_bar(stat = "identity", alpha = 0.7) +  # Bars for 'Actual'
  labs(x = "Individual", y = "Actual - Predicted (ng/mL)") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = custom_colors) +  # Apply the custom color palette
  guides(fill = guide_legend(nrow = 3, byrow = TRUE))  # Adjust legend to have three rows
# Save the plot
plot_filename_scatter <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/3_Omic_measurements/Actual_vs_Predicted_difference.png')
ggsave(plot_filename_scatter, p_bar_two, width = 7, height = 4)


```

# Sensitivity Analysis
```{r}
# Load in data
dat <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\Models\\3_Omic_measurements\\pysr_RMSE_sensitivity.csv')

# convert complexity to factor
dat$Complexity <- as.factor(dat$Complexity)

# Plot
p <- ggplot(dat, aes(x = Iteration, y = log(RMSE), color = Complexity)) +
  geom_point() +
  theme_classic() + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  theme(legend.position = "none") +
  theme(
    axis.text.x = element_text(size = 14),  
    axis.text.y = element_text(size = 14),  
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold")
  ) +
  guides(color = guide_legend(nrow = 2)) 

# Save
plot_filename <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/3_Omic_measurements/sensitivity.png')
  ggsave(plot_filename, p, width = 4, height = 4)
```

# Plot pathways
```{r}
top_diseases <- read.table('C://Users//Jessie PC//OneDrive - University of North Carolina at Chapel Hill//Symbolic_regression_github//NIH_Cloud_NOSI//Data_inputs//3_Omic_measurements//top_diseases.txt', header = TRUE, sep = "\t", stringsAsFactors = FALSE)

# Function to extract the minimum p-value from the p.value string
extract_min_pval <- function(pvalue_str) {
  # Split on hyphens not preceded by 'E'
  pval_parts <- strsplit(pvalue_str, "(?<!E)-", perl = TRUE)[[1]]
  # Remove any whitespace
  pval_parts <- trimws(pval_parts)
  # Convert to numeric
  pvals <- as.numeric(pval_parts)
  # Take the minimum value
  min_pval <- min(pvals, na.rm = TRUE)
  return(min_pval)
}

# Apply the function to the p.value column
top_diseases <- top_diseases %>%
  mutate(
    p_min = sapply(p.value, extract_min_pval),
    p_transformed = -log10(p_min)  # Transform p-values to -log10 scale
  )

# Subset the top 15 rows by p.value
top_15_diseases <- top_diseases %>%
  arrange(p.value) %>%
  slice(1:15)

# Subset the top 15 rows by the smallest p-value
top_15_diseases <- top_diseases %>%
  arrange(p_min) %>%
  slice(1:15)

# Create the bar chart
p <- ggplot(top_15_diseases, aes(x = reorder(Category, p_transformed), y = p_transformed)) +
  geom_bar(stat = "identity") +
  coord_flip() +  # Flip coordinates for better readability
  labs(
    x = NULL,  # Remove the 'Category' label
    y = "-log10(p-value)",
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold")
  ) +
  scale_y_continuous(expand = c(0, 0))  

# Read the data
top_pathways <- read.table(
  'C://Users//Jessie PC//OneDrive - University of North Carolina at Chapel Hill//Symbolic_regression_github//NIH_Cloud_NOSI//Data_inputs//3_Omic_measurements//top_pathways.txt',
  header = TRUE, sep = "\t", stringsAsFactors = FALSE
)
colnames(top_pathways)[2] <- 'p_transformed'

# Subset the top 15 pathways by the smallest p-value
top_15_pathways <- top_pathways %>%
  arrange(-p_transformed) %>%
  slice(1:15)

# Create the bar chart with adjustments
p <- ggplot(top_15_pathways, aes(x = reorder(Ingenuity.Canonical.Pathways, p_transformed), y = p_transformed)) +
  geom_bar(stat = "identity") +
  coord_flip() +  # Flip coordinates for better readability
  labs(
    x = NULL,  # Remove the 'Category' label
    y = "-log10(p-value)",
    title = "Top 15 Pathways by p-value"
  ) +
  theme_classic() +
  theme(
    axis.text.x = element_text(size = 12),
    axis.text.y = element_text(size = 12),
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold")
  ) +
  scale_y_continuous(expand = c(0, 0))  # Remove padding to make bars touch x-axi

```

