---
title: "Plot_results"
output: html_document
date: "2024-09-13"
---

# Libraries
```{r}
library(tidyverse)
library(reticulate)
library(Metrics)
repl_python()
```

```{python}
import pandas as pd
import pickle
import os

# Set working directory
os.chdir(r"C:\Users\Jessie PC\OneDrive - University of North Carolina at Chapel Hill\Symbolic_regression_github\NIH_Cloud_NOSI")

# Load in data
train_y = pd.read_pickle("Data_inputs/2_Chemical_measurements/train_y")
test_y = pd.read_pickle("Data_inputs/2_Chemical_measurements/test_y")
train_y_pred = pd.read_pickle("Data_inputs/2_Chemical_measurements/training_predictions_Full")
test_y_pred = pd.read_pickle("Data_inputs/2_Chemical_measurements/test_predictions_Full")
train_y_pred_pca = pd.read_pickle("Data_inputs/2_Chemical_measurements/training_predictions_PCA")
test_y_pred_pca = pd.read_pickle("Data_inputs/2_Chemical_measurements/test_predictions_PCA")
train_y_pred_elastic = pd.read_pickle("Data_inputs/2_Chemical_measurements/training_predictions_Elastic")
test_y_pred_elastic = pd.read_pickle("Data_inputs/2_Chemical_measurements/test_predictions_Elastic")
train_y_pred_rf = pd.read_pickle("Data_inputs/2_Chemical_measurements/training_predictions_rf_Full")
test_y_pred_rf = pd.read_pickle("Data_inputs/2_Chemical_measurements/test_predictions_rf_Full")


# Store the inputs (Full, PCA, Elastic) in a list
input_names = ['Full', 'PCA', 'Elastic', 'RF']
train_preds_list = [train_y_pred, train_y_pred_pca, train_y_pred_elastic, train_y_pred_rf]
test_preds_list = [test_y_pred, test_y_pred_pca, test_y_pred_elastic, test_y_pred_rf]
```

# Convert to r variables clean
```{r}
# Assign the list from Python to R variables
input_names <- py$input_names
train_preds_list <- py$train_preds_list
test_preds_list <- py$test_preds_list
train_y <- py$train_y
test_y <- py$test_y

# Combine all testing data into a single DataFrame with identifiers for each dataset and input name
combined_test_dat <- do.call(rbind, lapply(seq_along(input_names), function(i) {
  input_name <- input_names[[i]]
  test_y_pred <- test_preds_list[[i]]
  
  # Combine testing data into one DataFrame with 'Actual' and 'Predicted' columns
  test_combined <- data.frame(
    Actual = test_y,
    Predicted = test_y_pred[,1]
  )
  
  
  # Calculate difference between actual and predicted
  test_df <- test_combined %>%
    mutate(Dif = Actual - Predicted)
  
  # Calculate % error
  test_df <- test_df %>%
    mutate(perc_error = (Predicted - Actual)/ Predicted * 100)
    
  
  # Extract the rownames and modify them to contain only the part before the first '_'
  Group <- gsub("_.*", "", rownames(test_df))
  
  # Add 'Group' and 'input_name' as new columns to the DataFrame
  test_df$Group <- Group
  test_df$input_name <- input_name
  
  return(test_df)
}))

# Calculate normalized RMSE
nrmse <- rmse(combined_test_dat$Actual, combined_test_dat$Predicted) / (max(combined_test_dat$Actual)- min(combined_test_dat$Actual))
```

# Plot SRA results
```{r}
# Define levels
combined_test_dat$input_name <- factor(combined_test_dat$input_name, levels = c('Full', 'PCA', 'Elastic', 'RF'))

# Clean up group labels
combined_test_dat$Group <- gsub("Smoldering", "Smold.", combined_test_dat$Group)
combined_test_dat$Group <- gsub("Flaming", "Flam.", combined_test_dat$Group)
combined_test_dat$Group <- gsub("([a-z])([A-Z])", "\\1 \\2", combined_test_dat$Group)

# Define the custom group order
custom_order <- c("Red Oak Flam.", "Pine Flam.", "Peat Flam.", 
                  "Pine Needles Smold.", "Pine Needles Flam.", 
                  "Eucalyptus Smold.", "Eucalyptus Flam.", 
                  "Red Oak Smold.", "Pine Smold.", "Peat Smold.")
custom_order <- rev(custom_order)  # Reverse the order

# Update the Group variable with the custom order
combined_test_dat$Group <- factor(combined_test_dat$Group, levels = custom_order)

# Arrange the data by 'Group' and then by 'Actual' in descending order
combined_test_dat <- combined_test_dat %>%
  arrange(desc(Group), desc(Actual))

# Update the x-axis with the reordered factor levels
combined_test_dat$rownames <- factor(rownames(combined_test_dat), levels = rownames(combined_test_dat))

# Subset
combined_test_dat <- combined_test_dat %>%
  filter(input_name == 'Full')


# Define a custom color palette for the groups
custom_colors <- c(
  "Pine Flam." = "#1b9e77",
  "Peat Flam." = "#d95f02",
  "Red Oak Smold." = "#7570b3",
  "Eucalyptus Smold." = "#e7298a",
  "Pine Needles Flam." = "#66a61e",
  "Pine Needles Smold." = "#e6ab02",
  "Red Oak Flam." = "#a6761d",
  "Eucalyptus Flam." = "#666666",
  "Pine Smold." = "#1f78b4",
  "Peat Smold." = "#b2df8a"
)

# Set up the box plot using facet_wrap for each input_name
p <- ggplot(combined_test_dat, aes(x = Group, y = Dif, fill = Group)) +
  geom_boxplot() +
  geom_point(position = position_jitter(width = 0.2), alpha = 0.5) +
  labs(x = "Group", y = "Actual - Predicted (mg/mL)") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 12, face = "bold"),
    axis.title.y = element_text(size = 12, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 10),
    legend.position = "bottom"
  ) +
  scale_fill_manual(values = custom_colors) +  # Apply the custom color palette
  guides(fill = guide_legend(nrow = 3, byrow = TRUE)) +  # Adjust legend to have three rows
  facet_wrap(~ input_name, scales = "free_x")

# Print the combined plot
print(p)
# Save
plot_filename <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/2_Chemical_measurements/pysr/Prediction_spread_all.png')
ggsave(plot_filename, p, width = 7, height = 4)

# Set up the bar plot using facet_wrap for each input_name, using Individual_ID as the x-axis
p_bar <- ggplot(combined_test_dat, aes(x = combined_test_dat$rownames, y = Actual, fill = Group)) +
  geom_bar(stat = "identity", alpha = 0.7) +  # Bars for 'Actual'
  geom_point(aes(y = Predicted), color = "red", size = 3, shape = 95) +  # Red dash for 'Predicted'
  labs(x = "Individual", y = "Measured Injury Protein (ng/mL)") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 14),
    legend.position = "bottom"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = custom_colors) +  # Apply the custom color palette
  facet_wrap(~ input_name, scales = "free_x") +
  guides(fill = guide_legend(nrow = 3, byrow = TRUE))  # Adjust legend to have three rows
plot_filename <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/2_Chemical_measurements/pysr/Prediction_vs_actual_all.png')
ggsave(plot_filename, p_bar, width = 7, height = 4)

# Set up the bar plot using facet_wrap for each input_name, using Individual_ID as the x-axis
p_bar_two <- ggplot(combined_test_dat, aes(x = combined_test_dat$rownames, y = perc_error, fill = Group)) +
  geom_bar(stat = "identity", alpha = 0.7) +  # Bars for 'Actual'
  labs(x = "Individual", y = "Percent error") +
  theme_classic() +
  theme(
    axis.text.x = element_blank(),  # Remove x-axis text labels
    axis.title.x = element_text(size = 16, face = "bold"),
    axis.title.y = element_text(size = 16, face = "bold"),
    legend.title=element_blank(),
    legend.text = element_text(size = 14),
    legend.position = "bottom"
  ) +
  scale_y_continuous(expand = c(0,0)) +
  scale_fill_manual(values = custom_colors) +  # Apply the custom color palette
  facet_wrap(~ input_name, scales = "free_x") +
  guides(fill = guide_legend(nrow = 3, byrow = TRUE))  # Adjust legend to have three rows
# Save the plot
plot_filename_scatter <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/2_Chemical_measurements/pysr/Actual_vs_Predicted_difference.png')
ggsave(plot_filename_scatter, p_bar_two, width = 7, height = 4)

```


# Sensitivity analysis
```{r}
# Load in data
sens_full <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\Models\\2_Chemical_measurements\\pysr\\pysr_RMSE_sensitivity_Full.csv')
sens_pca <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\Models\\2_Chemical_measurements\\pysr\\pysr_RMSE_sensitivity_PCA.csv')
sens_elastic <- sens_full <- read.csv('C:\\Users\\Jessie PC\\OneDrive - University of North Carolina at Chapel Hill\\Symbolic_regression_github\\NIH_Cloud_NOSI\\Models\\2_Chemical_measurements\\pysr\\pysr_RMSE_sensitivity_elastic.csv')

# Put in list
dat_list <- list(sens_full, sens_pca, sens_elastic)
names(dat_list) <- c('Full', 'PCA', 'Elastic net')

# Combine and add a column for the dataset name
dat_all <- bind_rows(
  lapply(names(dat_list), function(name) {
    dat_list[[name]] %>%
      mutate(Dataset = name)
  })
)

# Make complexity a factor
dat_all$Complexity <- as.factor(dat_all$Complexity)

# Iterate through tests and create plots
tests <- unique(dat_all$Dataset)
for(i in 1:length(tests)){
  temp <- dat_all %>%
    filter(Dataset == tests[i])
  
  # Plot
  p <- ggplot(temp, aes(x = Iteration, y = log(RMSE), color = Complexity)) +
    geom_point() +
    theme_classic() + 
    ggtitle(tests[i]) +
    theme(plot.title = element_text(hjust = 0.5)) + 
    # theme(legend.position="bottom") + 
    guides(color = guide_legend(ncol = 2)) +
    theme(
      axis.text.x = element_text(size = 14), 
      axis.text.y = element_text(size = 14), 
      axis.title.x = element_text(size = 16, face = "bold"),
      axis.title.y = element_text(size =16, face = "bold")
    )
  
  # Save
  plot_filename <- paste0('C:/Users/Jessie PC/OneDrive - University of North Carolina at Chapel Hill/Symbolic_regression_github/NIH_Cloud_NOSI/images/2_Chemical_measurements/pysr/sensitivity', tests[i], '.png')
  ggsave(plot_filename, p, width = 8, height = 4)
}


```

